package mn.innex.stay.booking.domain;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import mn.innex.stay.common.Money;
import mn.innex.stay.listing.domain.CancellationPolicy;
import mn.innex.stay.listing.domain.Property;
import mn.innex.stay.user.domain.User;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.UuidGenerator;

/**
 * A guest's reservation of a listing.
 *
 * <p>Two things are snapshotted at creation rather than read live: the price
 * breakdown and the cancellation policy. A later change to the listing's price or
 * terms must not alter a stay someone has already agreed to, and a payout must be
 * explainable months later from the booking row alone.
 *
 * <p>The host is stored directly as well as through the property, because the
 * counterparty is the owner at the time of booking even if the listing later
 * changes hands.
 */
@Entity
@Table(name = "bookings")
public class Booking {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.VERSION_7)
    private UUID id;

    /** Short code quoted in support conversations, e.g. {@code SB-7KQ2M9}. */
    @Column(nullable = false, length = 16, unique = true)
    private String reference;

    @Enumerated(EnumType.STRING)
    @Column(name = "booking_type", nullable = false, length = 16)
    private BookingType bookingType = BookingType.PROPERTY;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "property_id")
    private Property property;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "guest_user_id", nullable = false)
    private User guest;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "host_user_id", nullable = false)
    private User host;

    @Column(name = "check_in", nullable = false)
    private LocalDate checkIn;

    @Column(name = "check_out", nullable = false)
    private LocalDate checkOut;

    /** Generated by Postgres from the date range; read-only here. */
    @Generated
    @Column(name = "nights", insertable = false, updatable = false)
    private Integer nights;

    @Column(name = "guest_count", nullable = false)
    private int guestCount = 1;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 28)
    private BookingStatus status;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 24)
    private BookingPaymentStatus paymentStatus = BookingPaymentStatus.UNPAID;

    @Column(nullable = false, length = 3)
    private String currency = "MNT";

    @Column(name = "nightly_subtotal", nullable = false, precision = 14, scale = 2)
    private BigDecimal nightlySubtotal = Money.ZERO;

    @Column(name = "cleaning_fee", nullable = false, precision = 14, scale = 2)
    private BigDecimal cleaningFee = Money.ZERO;

    @Column(name = "guest_service_fee", nullable = false, precision = 14, scale = 2)
    private BigDecimal guestServiceFee = Money.ZERO;

    @Column(nullable = false, precision = 14, scale = 2)
    private BigDecimal tax = Money.ZERO;

    @Column(nullable = false, precision = 14, scale = 2)
    private BigDecimal total = Money.ZERO;

    @Column(name = "host_commission", nullable = false, precision = 14, scale = 2)
    private BigDecimal hostCommission = Money.ZERO;

    @Column(name = "host_payout", nullable = false, precision = 14, scale = 2)
    private BigDecimal hostPayout = Money.ZERO;

    @Column(name = "commission_rule_id")
    private UUID commissionRuleId;

    @Enumerated(EnumType.STRING)
    @Column(name = "cancellation_policy", nullable = false, length = 16)
    private CancellationPolicy cancellationPolicy;

    @Column(name = "guest_message", columnDefinition = "text")
    private String guestMessage;

    @Column(name = "host_response_note", columnDefinition = "text")
    private String hostResponseNote;

    /** Deadline for the current pending state: host response, or payment hold. */
    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "approved_at")
    private Instant approvedAt;

    @Column(name = "confirmed_at")
    private Instant confirmedAt;

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Column(name = "cancelled_by")
    private UUID cancelledBy;

    @Column(name = "cancellation_reason", columnDefinition = "text")
    private String cancellationReason;

    @Column(name = "refund_amount", precision = 14, scale = 2)
    private BigDecimal refundAmount;

    @Column(name = "completed_at")
    private Instant completedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    private Long version;

    protected Booking() {
    }

    public Booking(String reference, Property property, User guest, LocalDate checkIn,
                   LocalDate checkOut, int guestCount, BookingStatus status, String guestMessage) {
        this.reference = reference;
        this.property = property;
        this.guest = guest;
        this.host = property.getOwner();
        this.checkIn = checkIn;
        this.checkOut = checkOut;
        this.guestCount = guestCount;
        this.status = status;
        this.guestMessage = guestMessage;
        this.currency = property.getCurrency();
        this.cancellationPolicy = property.getCancellationPolicy();
    }

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }

    /** Copies a computed quote onto the booking. The database CHECK verifies the total adds up. */
    public void applyPricing(BigDecimal nightlySubtotal, BigDecimal cleaningFee,
                             BigDecimal guestServiceFee, BigDecimal tax, BigDecimal total,
                             BigDecimal hostCommission, BigDecimal hostPayout, UUID commissionRuleId) {
        this.nightlySubtotal = Money.of(nightlySubtotal);
        this.cleaningFee = Money.of(cleaningFee);
        this.guestServiceFee = Money.of(guestServiceFee);
        this.tax = Money.of(tax);
        this.total = Money.of(total);
        this.hostCommission = Money.of(hostCommission);
        this.hostPayout = Money.of(hostPayout);
        this.commissionRuleId = commissionRuleId;
    }

    public void approve(Instant paymentDeadline, String note) {
        this.status = BookingStatus.PENDING_PAYMENT;
        this.approvedAt = Instant.now();
        this.expiresAt = paymentDeadline;
        this.hostResponseNote = note;
    }

    public void decline(String note) {
        this.status = BookingStatus.DECLINED;
        this.hostResponseNote = note;
        this.expiresAt = null;
    }

    public void markPaidAndConfirm() {
        this.status = BookingStatus.CONFIRMED;
        this.paymentStatus = BookingPaymentStatus.PAID;
        this.confirmedAt = Instant.now();
        // The hold is over; the dates are held by CONFIRMED from here.
        this.expiresAt = null;
    }

    public void markPaymentProcessing() {
        this.paymentStatus = BookingPaymentStatus.PROCESSING;
    }

    public void markPaymentFailed() {
        this.paymentStatus = BookingPaymentStatus.FAILED;
    }

    public void expire() {
        this.status = BookingStatus.EXPIRED;
        this.expiresAt = null;
    }

    public void cancel(BookingStatus cancelledStatus, UUID actorId, String reason,
                       BigDecimal refundAmount) {
        this.status = cancelledStatus;
        this.cancelledAt = Instant.now();
        this.cancelledBy = actorId;
        this.cancellationReason = reason;
        this.refundAmount = refundAmount == null ? null : Money.of(refundAmount);
        this.expiresAt = null;
        if (Money.isPositive(refundAmount)) {
            this.paymentStatus = Money.of(refundAmount).compareTo(total) >= 0
                    ? BookingPaymentStatus.REFUNDED
                    : BookingPaymentStatus.PARTIALLY_REFUNDED;
        }
    }

    public void complete() {
        this.status = BookingStatus.COMPLETED;
        this.completedAt = Instant.now();
    }

    public boolean isGuest(UUID userId) {
        return guest != null && guest.getId().equals(userId);
    }

    public boolean isHost(UUID userId) {
        return host != null && host.getId().equals(userId);
    }

    /** Nights, computed locally so it is available before the entity is reloaded. */
    public int nightCount() {
        return nights != null ? nights : (int) ChronoUnit.DAYS.between(checkIn, checkOut);
    }

    public UUID getId() {
        return id;
    }

    public String getReference() {
        return reference;
    }

    public BookingType getBookingType() {
        return bookingType;
    }

    public Property getProperty() {
        return property;
    }

    public User getGuest() {
        return guest;
    }

    public User getHost() {
        return host;
    }

    public LocalDate getCheckIn() {
        return checkIn;
    }

    public LocalDate getCheckOut() {
        return checkOut;
    }

    public int getGuestCount() {
        return guestCount;
    }

    public BookingStatus getStatus() {
        return status;
    }

    public BookingPaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public String getCurrency() {
        return currency;
    }

    public BigDecimal getNightlySubtotal() {
        return nightlySubtotal;
    }

    public BigDecimal getCleaningFee() {
        return cleaningFee;
    }

    public BigDecimal getGuestServiceFee() {
        return guestServiceFee;
    }

    public BigDecimal getTax() {
        return tax;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public BigDecimal getHostCommission() {
        return hostCommission;
    }

    public BigDecimal getHostPayout() {
        return hostPayout;
    }

    public UUID getCommissionRuleId() {
        return commissionRuleId;
    }

    public CancellationPolicy getCancellationPolicy() {
        return cancellationPolicy;
    }

    public String getGuestMessage() {
        return guestMessage;
    }

    public String getHostResponseNote() {
        return hostResponseNote;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public Instant getApprovedAt() {
        return approvedAt;
    }

    public Instant getConfirmedAt() {
        return confirmedAt;
    }

    public Instant getCancelledAt() {
        return cancelledAt;
    }

    public UUID getCancelledBy() {
        return cancelledBy;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        return other instanceof Booking booking && id != null && id.equals(booking.id);
    }

    @Override
    public int hashCode() {
        return id == null ? System.identityHashCode(this) : id.hashCode();
    }
}
